# Generated by Django 5.2.6 on 2025-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(upload_to='housingwalaa/promotions/'),
        ),
    ]
