# Generated by Django 5.2.6 on 2025-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('PLOT', 'Plot')], max_length=30)),
                ('status', models.CharField(choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('READY', 'Ready to Move'), ('UPCOMING', 'Upcoming')], max_length=30)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('FLOORPLAN', 'Floorplan'), ('VIDEO', 'Video')], max_length=20)),
                ('file', models.ImageField(blank=True, null=True, upload_to='property/media/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=50)),
                ('size_sqft', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
