# Generated by Django 5.2.6 on 2025-09-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
