# Generated by Django 5.2.6 on 2025-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_amenity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='properties',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity'),
        ),
    ]
