# Generated by Django 5.2.6 on 2025-09-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_location_property_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
