# Generated by Django 5.2.6 on 2025-10-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='housingwalaa/developers/logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unitplan',
            name='size_sqft',
        ),
        migrations.AddField(
            model_name='property',
            name='brochure_pdf',
            field=models.FileField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AddField(
            model_name='property',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='balconies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='builtup_area_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='carpet_area_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='housingwalaa/unit_plans/'),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitplan',
            name='super_builtup_area_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('FLOORPLAN', 'Floorplan'), ('VIDEO', 'Video'), ('VIRTUAL_TOUR', 'Virtual Tour')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='properties.developer'),
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('travel_time_min', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_towers', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('project_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('open_area_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parking_type', models.CharField(blank=True, max_length=200, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('project_position', models.CharField(blank=True, max_length=100, null=True)),
                ('road_connectivity', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_banks', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='properties.property')),
            ],
        ),
    ]
