# Generated by Django 5.2.6 on 2025-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
